# version: "3.5"

# volumes:
#         wordpress:
#                 name: wordpress
#                 driver: local
#                 driver_opts:
#                         device: /Users/sahafid/Desktop/Inception/srcs/wordpress
#                         o: bind
#                         type: none
#         mariadb:
#                 name: mariadb
#                 driver: local
#                 driver_opts:
#                         device: /Users/sahafid/Desktop/Inception/srcs/mariadb
#                         o: bind
#                         type: none

# networks:
#   inception:
#     name: inception

# services:
#   nginx:
#     container_name: nginx
#     build: ./requirements/nginx/.
#     image: nginx:42
#     ports:
#      - "443:443"
#     depends_on:
#       - wordpress
#     volumes:
#      - wordpress:/var/www/html
#     networks:
#       - inception
#     env_file:
#       - .env
#     restart: always
#   wordpress:
#     container_name: wordpress
#     build: ./requirements/wordpress/.
#     image: wordpress:42
#     depends_on:
#       - mariadb
#     volumes:
#       - wordpress:/var/www/html
#     env_file:
#       - .env
#     networks:
#       - inception
#     restart: always
#   mariadb:
#     container_name: mariadb
#     build: ./requirements/mariadb/.
#     image: mariadb:42
#     volumes:
#       - mariadb:/var/lib/mysql
#     env_file:
#       - .env
#     networks:
#       - inception
#     restart: always
  # ftp:
  #   container_name: ftp
  #   build: ./requirements/bonus/ftp/.
  #   image: ftp:42
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wordpress:/home/sami/ftp/files
  #   env_file:
  #     - .env
  #   ports:
  #     - "21:21"
  #     - "20:20"
  #     - "40000-40005:40000-40005"
  #   networks:
  #     - inception
  #   restart: always
  # adminer:
  #   container_name: adminer
  #   build: ./requirements/bonus/adminer/.
  #   image: adminer:42
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "600:80"
  #   networks:
  #     - inception
  #   restart: always
  # redis:
  #   container_name: redis
  #   build: ./requirements/bonus/redis/.
  #   image: redis:42
  #   volumes:
  #    - wordpress:/var/www/html
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - inception
  #   restart: always
  # website:
  #   container_name: website
  #   build: ./requirements/bonus/websites/.
  #   image: website:42
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - inception
  #   restart: always
  # cadvisor:
  #   container_name: cadvisor
  #   build: ./requirements/bonus/cadvisor/.
  #   image: cadvisor:42
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - inception
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro 
  #     - /sys:/sys:ro 
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: always




version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - adminer
      - redis
      - hugo
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes allow to store in a persistent disk the content in a local disk
    #db_data is a volume created by docker directly
    volumes:
      - mariadb_data:/var/lib/mysql
    # in case of problem we restart automatically the container
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    #Create a depedency between the 2 container, db will be launched before
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

#BONUS PART
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  ftp-server:
    build: requirements/bonus/ftp_server
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress_data:/var/www/html"
    networks:
      - network
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}

  adminer:
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - network

  hugo:
    container_name: hugo
    build: ./requirements/bonus/hugo
    restart: always
    networks:
      - network

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: always
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vbachele/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vbachele/data/wordpress
      o: bind

networks:
  network:
    driver: bridge