version: '3.8'
services:
  adminer:
    container_name: Adminer     # name redirect to IP -> 172.x.x.x
    build: Adminer/.            # build the dockerfile in this adminer_directory
    restart: always             # restart the container if it stops
    ports:
      - "80:80"                 # redirect port 80 of Adminer on the host
    networks:
      - mynetwork               # use mynetwork for communication with mariadb

  mariadb:
    container_name: Mariadb
    build: Mariadb/.
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file: .env

  nginx:
    container_name: nginx
    build: ./NGINX/
    restart: always
    volumes:
      - WordPress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: ./wordpress/
    restart: always
    volumes:
      - WordPress:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mateo/Desktop/Inception/rendu_inception/Inception_bis/my_volume'

  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mateo/data/website