# Generated by Django 5.1.3 on 2025-04-11 11:36

import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=users.models.avatar_upload_path, validators=[users.validators.validate_avatar]),
        ),
    ]
