# Generated by Django 5.1.3 on 2025-05-02 17:41

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_login_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_42',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[users.validators.validate_not_banned_username]),
        ),
    ]
