# Generated by Django 5.1.3 on 2025-04-10 16:32

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/', validators=[users.validators.validate_avatar]),
        ),
    ]
