# Generated by Django 5.1.3 on 2025-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_42',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
