# Generated by Django 5.1.3 on 2025-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_login_42_customuser_preferred_language_and_more'),
        ('users', '0008_customuser_preferred_language'),
        ('users', '0009_alter_customuser_username'),
    ]

    operations = [
    ]
