# Generated by Django 5.1.3 on 2025-05-05 18:19

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_login_42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[users.validators.validate_not_banned_username], verbose_name='Username'),
        ),
    ]
