# Generated by Django 5.1.3 on 2025-05-06 20:45

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[users.validators.validate_not_banned_username, users.validators.validate_min_username_length], verbose_name='Username'),
        ),
    ]
