services:
  django:
    container_name: django
    # image: django_image
    # tty: true
    build: ./the_transcendence
    ports:
      - 8800:8800
    volumes:
      - ./the_transcendence:/the_transcendence
    # depends_on:
    #   - db_postgresql
        # condition: service_healthy
  # db_postgresql:
  #   container_name: db_postgresql
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_DB: postgres_db
  #     POSTGRES_USER: postgres_user
  #     POSTGRES_PASSWORD: postgres_pass