services:
  db:
    container_name: db_the_transcendence
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - dev.env

  the_transcendence:
    build:
      context: ./lets_see/
      dockerfile: Dockerfile.dev
    container_name: the_transcendence
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - dev.env
    expose:
      - 8000
    volumes:
      - ./lets_see:/app

volumes:
  postgres_data: