services:
  db:
    container_name: db_the_transcendence
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  the_transcendence:
    build:
      context: ./lets_see/
      dockerfile: Dockerfile.prod
    container_name: the_transcendence
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - ./lets_see:/app
      - ./lets_see/media:/app/media
      - ./lets_see/static:/app/static
      - ./lets_see/staticfiles:/app/staticfiles

  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./lets_see/media:/app/media
      - ./lets_see/static:/app/static
      - ./lets_see/staticfiles:/app/staticfiles
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      the_transcendence:
        condition: service_started

volumes:
  postgres_data:
  caddy_data:
  caddy_config: