services:
  db:
    container_name: db_the_transcendence
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  the_transcendence:
    build:
      context: ./lets_see/
      dockerfile: Dockerfile.prod
    container_name: the_transcendence
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}

      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - ./lets_see/media:/app/media
      - ./lets_see/static:/app/static

  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./lest_see/media:/app/media
      - ./lets_see/static:/app/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - the_transcendence

volumes:
  postgres_data:
  caddy_data:
  caddy_config: