services:
  django:
    container_name: django
    # image: django_image
    tty: true
    build: .
    ports:
      - 8880:8880
    # depends_on:
    #   - db_postgresql
        # condition: service_healthy
  # db_postgresql:
  #   container_name: db_postgresql
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_DB: postgres_db
  #     POSTGRES_USER: postgres_user
  #     POSTGRES_PASSWORD: postgres_pass