# Generated by Django 5.1.3 on 2025-04-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_du_pong', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
