# Generated by Django 5.1.3 on 2025-04-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_login_42'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login_42',
        ),
    ]
