# Generated by Django 5.1.3 on 2025-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_login_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_42',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
