# Generated by Django 5.1.3 on 2025-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_login_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
