# Generated by Django 5.1.3 on 2025-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20250503_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_42',
            field=models.CharField(max_length=30),
        ),
    ]
