version: '3.8'

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mateo/data/db'
  wp:
    name: wp
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mateo/data/wp'

services:
  mariadb:
    container_name: Mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file: 
      - .env 
    restart: always
    expose:
      - "3306"
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

networks:
  inception:
    driver: bridge
